title: Crash Bandit Photography
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.625
  brandStrength: 0
  rhythmicContrast: 0.5
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#2f2f2f'
    - '#afafaf'
    - '#868686'
  lightness: 0.1875
cta:
  bucket: null
  version: null
  domain: null
name: 'Crashbanditphotography '
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.67651
layout_spectrum: 0
