name: 'Crashbanditphotography '
favicon: null
layout_spectrum: 0.49433
typography_spectrum: 0.67651
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#bbaea6'
    - '#6c380d'
    - '#930006'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
