layout_spectrum: 0.234767
typography_spectrum: 0.8343582
color:
  saturation: 0.5215054
  brandStrength: 0.153646
  lightness: 0.7634408
  rhythmicContrast: 0.811828
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: 'Crashbanditohotography '
